"""
================================================================================
PUCCH Format 0 - Machine Learning Decoder
Main Execution Script
================================================================================

This is the main entry point for the PUCCH Format 0 ML Decoder.

It orchestrates the complete pipeline:
    1. System information and configuration display
    2. Data loading from CSV files
    3. Data analysis and validation
    4. Data splitting (train/validation/test)
    5. Data preprocessing
    6. Neural network creation
    7. Model training
    8. Model evaluation on all SNR values
    9. Comparison with correlation-based decoder
    10. Visualization (all plots)
    11. Results saving

Usage:
    python main.py

Requirements:
    - CSV data files generated by MATLAB (pucch_f0_dataset_SNR_XdB.csv)
    - All module files (config.py, data_loader.py, data_preprocessing.py,
      model.py, evaluation.py, visualization.py)

================================================================================
"""

import os
import sys
import time
import datetime
import numpy as np

# Import project modules
from config import config
from data_loader import load_all_datasets, analyze_dataset
from data_preprocessing import prepare_data, preprocess_pipeline
from model import (
    set_random_seeds,
    create_model,
    train_model,
    load_saved_model,
    get_training_summary,
    print_gpu_info,
    print_tensorflow_info
)
from evaluation import (
    evaluate_all_snr,
    generate_all_classification_reports,
    compare_nn_vs_correlation,
    save_evaluation_results,
    save_confusion_matrices,
    save_experiment_summary
)
from visualization import generate_all_plots


# =============================================================================
# SECTION 1: SYSTEM INFORMATION
# =============================================================================

def print_system_info():
    """
    Print system information, library versions, and GPU availability.
    """

    print("\n" + "=" * 70)
    print("   PUCCH FORMAT 0 - MACHINE LEARNING DECODER")
    print("=" * 70)
    print(
        f"\nTimestamp: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Python: {sys.version.split()[0]}")
    print(f"NumPy: {np.__version__}")

    # TensorFlow info
    print_tensorflow_info()
    print_gpu_info()


# =============================================================================
# SECTION 2: CHECK DATA FILES
# =============================================================================

def check_data_files(verbose: bool = True) -> bool:
    """
    Check if all required data files exist.

    Parameters:
    -----------
    verbose : bool, default=True
        If True, print file status

    Returns:
    --------
    all_found : bool
        True if all required files exist
    """

    if verbose:
        print("\n" + "=" * 70)
        print("CHECKING DATA FILES")
        print("=" * 70)

    all_found = True
    found_count = 0
    missing_count = 0

    for snr in config.SNR_VALUES:
        filepath = config.get_data_filepath(snr)
        exists = os.path.exists(filepath)

        if exists:
            found_count += 1
            file_size = os.path.getsize(filepath) / (1024 * 1024)  # MB
            if verbose:
                print(
                    f"  [FOUND]   SNR {snr:3d} dB: {filepath} ({file_size:.1f} MB)")
        else:
            missing_count += 1
            all_found = False
            if verbose:
                print(f"  [MISSING] SNR {snr:3d} dB: {filepath}")

    if verbose:
        print(f"\nFound: {found_count}/{len(config.SNR_VALUES)} files")

        if not all_found:
            print("\nWARNING: Some data files are missing!")
            print("Please run the MATLAB data generation script first.")
            print(f"Expected files in: {os.path.abspath(config.DATA_DIR)}")

        print("=" * 70 + "\n")

    return all_found


# =============================================================================
# SECTION 3: MAIN PIPELINE
# =============================================================================

def run_pipeline(show_plots: bool = True, verbose: bool = True):
    """
    Run the complete ML pipeline.

    This function executes all steps in order:
        1. Print system info and configuration
        2. Check and load data files
        3. Analyze training dataset
        4. Prepare data splits
        5. Preprocess data
        6. Create neural network model
        7. Train model
        8. Load best model
        9. Evaluate on all SNR values
        10. Generate classification reports
        11. Compare with correlation decoder
        12. Generate all plots
        13. Save all results

    Parameters:
    -----------
    show_plots : bool, default=True
        If True, display plots during execution
        Set to False for batch/automated runs
    verbose : bool, default=True
        If True, print detailed progress information

    Returns:
    --------
    results : dict
        Dictionary containing all outputs:
        - 'model': Trained model
        - 'history': Training history
        - 'training_time': Training time in seconds
        - 'all_results': Evaluation results per SNR
        - 'comparison': NN vs Correlation comparison
        - 'training_summary': Summary of training

    Returns None if pipeline fails.
    """

    pipeline_start_time = time.time()

    # =========================================================================
    # STEP 1: System Information and Configuration
    # =========================================================================

    if verbose:
        print("\n")
        print("#" * 70)
        print("#" + " " * 20 + "STARTING PIPELINE" + " " * 31 + "#")
        print("#" * 70)

    print_system_info()
    config.print_config()

    # Validate configuration
    if not config.validate_config():
        print("ERROR: Configuration validation failed. Aborting.")
        return None

    # Create output directories
    config.create_directories()

    # =========================================================================
    # STEP 2: Set Random Seeds
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 1: Setting Random Seeds")
        print("=" * 70)

    set_random_seeds(seed=config.MASTER_SEED, verbose=True)

    # =========================================================================
    # STEP 3: Check and Load Data Files
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 2: Loading Data")
        print("=" * 70)

    # Check files exist
    files_exist = check_data_files(verbose=True)

    if not files_exist:
        print("\nERROR: Required data files not found!")
        print("Please run the MATLAB data generation script first.")
        return None

    # Load all datasets
    try:
        datasets = load_all_datasets(
            snr_values=config.SNR_VALUES,
            data_dir=config.DATA_DIR,
            validate=True,
            verbose=True
        )
    except Exception as e:
        print(f"\nERROR: Failed to load datasets: {e}")
        return None

    # Verify training SNR is available
    if config.TRAIN_SNR not in datasets:
        print(f"\nERROR: Training SNR {config.TRAIN_SNR} dB not loaded!")
        print(f"Available SNR values: {list(datasets.keys())}")
        return None

    # =========================================================================
    # STEP 4: Analyze Training Dataset
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 3: Analyzing Training Dataset")
        print("=" * 70)

    train_stats = analyze_dataset(
        X=datasets[config.TRAIN_SNR][0],
        y=datasets[config.TRAIN_SNR][1],
        name=f"Training Data (SNR = {config.TRAIN_SNR} dB)",
        verbose=True
    )

    # Check for data quality issues
    if train_stats['num_nan'] > 0:
        print("WARNING: NaN values found in training data!")
    if train_stats['num_inf'] > 0:
        print("WARNING: Inf values found in training data!")
    if not train_stats['is_balanced']:
        print("WARNING: Training data is not balanced!")

    # =========================================================================
    # STEP 5: Prepare Data Splits
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 4: Preparing Data Splits")
        print("=" * 70)

    try:
        X_train, y_train, X_val, y_val, X_test_dict, y_test_dict = prepare_data(
            datasets=datasets,
            train_snr=config.TRAIN_SNR,
            train_ratio=config.TRAIN_RATIO,
            random_seed=config.SKLEARN_SEED,
            verbose=True
        )
    except Exception as e:
        print(f"\nERROR: Failed to prepare data: {e}")
        return None

    # =========================================================================
    # STEP 6: Preprocess Data
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 5: Preprocessing Data")
        print("=" * 70)

    X_train_proc, X_val_proc, X_test_dict_proc, scaler = preprocess_pipeline(
        X_train=X_train,
        X_val=X_val,
        X_test_dict=X_test_dict,
        normalize=config.NORMALIZE_FEATURES,
        verbose=True
    )

    # =========================================================================
    # STEP 7: Create Neural Network Model
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 6: Creating Neural Network Model")
        print("=" * 70)

    model = create_model(
        input_size=config.INPUT_SIZE,
        hidden_layers=config.HIDDEN_LAYERS,
        output_size=config.OUTPUT_SIZE,
        hidden_activation=config.HIDDEN_ACTIVATION,
        output_activation=config.OUTPUT_ACTIVATION,
        dropout_rate=config.DROPOUT_RATE,
        use_dropout=config.USE_DROPOUT,
        kernel_initializer=config.KERNEL_INITIALIZER,
        learning_rate=config.LEARNING_RATE,
        momentum=config.MOMENTUM,
        use_nesterov=config.USE_NESTEROV,
        print_summary=True
    )

    # =========================================================================
    # STEP 8: Train Model
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 7: Training Model")
        print("=" * 70)

    model_filepath = config.get_model_filepath()

    try:
        history, training_time = train_model(
            model=model,
            X_train=X_train_proc,
            y_train=y_train,
            X_val=X_val_proc,
            y_val=y_val,
            epochs=config.NUM_EPOCHS,
            batch_size=config.BATCH_SIZE,
            model_filepath=model_filepath,
            verbose=1
        )
    except Exception as e:
        print(f"\nERROR: Training failed: {e}")
        return None

    # Get training summary
    training_summary = get_training_summary(history)

    # =========================================================================
    # STEP 9: Load Best Model
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 8: Loading Best Model")
        print("=" * 70)

    try:
        best_model = load_saved_model(filepath=model_filepath, verbose=True)
    except FileNotFoundError:
        print("WARNING: Best model file not found. Using last training state.")
        best_model = model

    # =========================================================================
    # STEP 10: Evaluate on All SNR Values
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 9: Evaluating Model")
        print("=" * 70)

    all_results = evaluate_all_snr(
        model=best_model,
        X_test_dict=X_test_dict_proc,
        y_test_dict=y_test_dict,
        verbose=True
    )

    # =========================================================================
    # STEP 11: Generate Classification Reports
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 10: Classification Reports")
        print("=" * 70)

    reports = generate_all_classification_reports(
        all_results=all_results,
        verbose=True
    )

    # =========================================================================
    # STEP 12: Compare with Correlation Decoder
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 11: Comparing with Correlation Decoder")
        print("=" * 70)

    comparison = compare_nn_vs_correlation(
        model=best_model,
        X_test_dict=X_test_dict_proc,
        y_test_dict=y_test_dict,
        X_train=X_train_proc,
        y_train=y_train,
        verbose=True
    )

    # =========================================================================
    # STEP 13: Generate All Plots
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 12: Generating Plots")
        print("=" * 70)

    generate_all_plots(
        history=history,
        all_results=all_results,
        comparison=comparison,
        show_plots=show_plots,
        verbose=True
    )

    # =========================================================================
    # STEP 14: Save All Results
    # =========================================================================

    if verbose:
        print("\n" + "=" * 70)
        print("STEP 13: Saving Results")
        print("=" * 70)

    # Save evaluation results CSV
    results_df = save_evaluation_results(
        all_results=all_results,
        comparison=comparison,
        filepath=os.path.join(config.RESULTS_DIR, config.RESULTS_FILENAME),
        verbose=True
    )

    # Save confusion matrices
    save_confusion_matrices(
        all_results=all_results,
        filepath=os.path.join(config.RESULTS_DIR, "confusion_matrices.txt"),
        verbose=True
    )

    # Save experiment summary
    save_experiment_summary(
        all_results=all_results,
        comparison=comparison,
        training_time=training_time,
        history=history,
        filepath=os.path.join(config.RESULTS_DIR, "experiment_summary.txt"),
        verbose=True
    )

    # =========================================================================
    # FINAL SUMMARY
    # =========================================================================

    pipeline_time = time.time() - pipeline_start_time

    print("\n")
    print("#" * 70)
    print("#" + " " * 20 + "PIPELINE COMPLETE" + " " * 31 + "#")
    print("#" * 70)

    print(
        f"\nTotal pipeline time: {pipeline_time:.1f} seconds ({pipeline_time/60:.2f} minutes)")
    print(
        f"\nTimestamp: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Training summary
    print(f"\n--- Training Summary ---")
    print(f"Epochs completed: {training_summary['epochs_completed']}")
    print(f"Training time: {training_time:.1f} seconds")
    print(f"Best validation accuracy: {training_summary['best_val_acc']:.2f}% "
          f"(epoch {training_summary['best_epoch']})")

    # Results summary
    print(f"\n--- Results Summary ---")
    print(f"{'SNR (dB)':<10}{'NN Acc (%)':<12}{'Corr Acc (%)':<14}{'Gain (%)':<10}")
    print("-" * 46)
    for i, snr in enumerate(comparison['snr']):
        nn_acc = comparison['nn_accuracy'][i]
        corr_acc = comparison['corr_accuracy'][i]
        gain = nn_acc - corr_acc
        print(f"{snr:<10}{nn_acc:<12.2f}{corr_acc:<14.2f}{gain:<+10.2f}")
    print("-" * 46)

    # Output files
    print(f"\n--- Output Files ---")
    print(f"Model: {model_filepath}")
    print(
        f"Results: {os.path.join(config.RESULTS_DIR, config.RESULTS_FILENAME)}")
    print(f"Plots: {config.PLOTS_DIR}")
    print(f"Logs: {config.LOGS_DIR}")
    print(
        f"Summary: {os.path.join(config.RESULTS_DIR, 'experiment_summary.txt')}")

    print("\n" + "#" * 70 + "\n")

    # Prepare return dictionary
    results = {
        'model': best_model,
        'history': history,
        'training_time': training_time,
        'training_summary': training_summary,
        'all_results': all_results,
        'comparison': comparison,
        'reports': reports,
        'results_df': results_df,
        'scaler': scaler,
        'X_train': X_train_proc,
        'y_train': y_train,
        'X_val': X_val_proc,
        'y_val': y_val,
        'X_test_dict': X_test_dict_proc,
        'y_test_dict': y_test_dict,
        'pipeline_time': pipeline_time
    }

    return results


# =============================================================================
# SECTION 4: EVALUATION ONLY MODE
# =============================================================================

def run_evaluation_only(
    model_filepath: str = None,
    show_plots: bool = True,
    verbose: bool = True
):
    """
    Run evaluation only using a previously trained model.

    This is useful when you want to re-evaluate or generate new plots
    without retraining the model.

    Parameters:
    -----------
    model_filepath : str, optional
        Path to the trained model
        Default: config.MODELS_DIR + config.MODEL_FILENAME
    show_plots : bool, default=True
        If True, display plots
    verbose : bool, default=True
        If True, print progress

    Returns:
    --------
    results : dict or None
        Dictionary containing evaluation results, or None if failed
    """

    if model_filepath is None:
        model_filepath = config.get_model_filepath()

    print("\n" + "=" * 70)
    print("EVALUATION ONLY MODE")
    print("=" * 70)

    # Set seeds
    set_random_seeds(config.MASTER_SEED, verbose=True)

    # Check model exists
    if not os.path.exists(model_filepath):
        print(f"ERROR: Model file not found: {model_filepath}")
        print("Please train a model first using run_pipeline()")
        return None

    # Load model
    try:
        model = load_saved_model(filepath=model_filepath, verbose=True)
    except Exception as e:
        print(f"ERROR: Failed to load model: {e}")
        return None

    # Check data files
    if not check_data_files(verbose=True):
        return None

    # Load data
    try:
        datasets = load_all_datasets(verbose=True)
    except Exception as e:
        print(f"ERROR: Failed to load data: {e}")
        return None

    # Prepare data
    try:
        X_train, y_train, X_val, y_val, X_test_dict, y_test_dict = prepare_data(
            datasets=datasets,
            verbose=True
        )
    except Exception as e:
        print(f"ERROR: Failed to prepare data: {e}")
        return None

    # Preprocess
    X_train_proc, X_val_proc, X_test_dict_proc, scaler = preprocess_pipeline(
        X_train=X_train,
        X_val=X_val,
        X_test_dict=X_test_dict,
        verbose=True
    )

    # Evaluate
    all_results = evaluate_all_snr(
        model=model,
        X_test_dict=X_test_dict_proc,
        y_test_dict=y_test_dict,
        verbose=True
    )

    # Classification reports
    reports = generate_all_classification_reports(
        all_results=all_results,
        verbose=True
    )

    # Compare with correlation
    comparison = compare_nn_vs_correlation(
        model=model,
        X_test_dict=X_test_dict_proc,
        y_test_dict=y_test_dict,
        X_train=X_train_proc,
        y_train=y_train,
        verbose=True
    )

    # Save results
    save_evaluation_results(
        all_results=all_results,
        comparison=comparison,
        verbose=True
    )

    print("\n" + "=" * 70)
    print("EVALUATION COMPLETE")
    print("=" * 70 + "\n")

    results = {
        'model': model,
        'all_results': all_results,
        'comparison': comparison,
        'reports': reports
    }

    return results


# =============================================================================
# SECTION 5: SCRIPT ENTRY POINT
# =============================================================================

if __name__ == "__main__":
    """
    Main entry point.

    Usage:
        python main.py              # Run full pipeline
        python main.py --eval-only  # Run evaluation only
        python main.py --no-plots   # Run without displaying plots
    """

    # Parse simple command line arguments
    show_plots = True
    eval_only = False

    if len(sys.argv) > 1:
        for arg in sys.argv[1:]:
            if arg == "--eval-only":
                eval_only = True
            elif arg == "--no-plots":
                show_plots = False
            elif arg == "--help":
                print("\nUsage: python main.py [options]")
                print("\nOptions:")
                print("  --eval-only   Run evaluation only (requires trained model)")
                print("  --no-plots    Run without displaying plots")
                print("  --help        Show this help message")
                print()
                sys.exit(0)
            else:
                print(f"Unknown argument: {arg}")
                print("Use --help for usage information")
                sys.exit(1)

    # Run selected mode
    if eval_only:
        results = run_evaluation_only(show_plots=show_plots)
    else:
        results = run_pipeline(show_plots=show_plots)

    # Check if pipeline completed successfully
    if results is not None:
        print("Pipeline completed successfully!")
    else:
        print("Pipeline failed. Please check the error messages above.")
        sys.exit(1)
