"""
PUCCH Format 0 - Multi-User Machine Learning Decoder
Main Execution Script (Research-Grade Implementation)

Novel Contribution:
==================
This script implements a machine learning-based decoder for PUCCH Format 0
in multi-user scenarios where multiple User Equipments (UEs) transmit 
simultaneously on the same time-frequency resources using different 
Initial Cyclic Shifts (m0).

Research Objectives:
-------------------
1. Interference Robustness: Train ML model to decode target user signal
   in the presence of inter-user interference from 1-2 interfering users.

2. Baseline Comparison: Comprehensive comparison with traditional 
   correlation-based decoder to quantify ML performance gains.

3. Multi-SNR Generalization: Model trained on single SNR (10 dB), 
   evaluated across wide SNR range (0-20 dB) to assess generalization.

4. Reproducibility: Full experiment logging, seed control, and result 
   saving for research reproducibility and peer verification.

Supported Scenarios:
-------------------
- 2 Users: Target (m0=0) + 1 Interferer (m0=1)
- 3 Users: Target (m0=0) + 2 Interferers (m0=1, m0=2)

Expected Results for Publication:
--------------------------------
- Accuracy vs SNR curves for NN and Correlation decoder
- Performance gain analysis (NN - Correlation)
- Confusion matrices per SNR value
- Computational complexity comparison

Usage:
------
    python main_multi_ue.py              # Run full pipeline with plots
    python main_multi_ue.py --no-plots   # Run without displaying plots
    python main_multi_ue.py --eval-only  # Evaluation only (requires trained model)
    python main_multi_ue.py --help       # Show help message

Requirements:
------------
- Multi-user CSV data files generated by MATLAB:
  * pucch_f0_2users_SNR_XdB.csv (for 2-user scenario)
  * pucch_f0_3users_SNR_XdB.csv (for 3-user scenario)
  
- All multi_ue module files:
  * config_multi_ue.py
  * data_loader_multi_ue.py
  * data_preprocessing_multi_ue.py
  * evaluation_multi_ue.py
  * model.py (base module)

Author: Research Team
Date: 2024
Version: 1.0
================================================================================
"""

# Fix for TensorFlow >= 2.16 (must be before tensorflow import)
from evaluation_multi_ue import (
    evaluate_all_snr,
    generate_all_classification_reports,
    compare_nn_vs_correlation,
    save_evaluation_results,
    save_confusion_matrices,
    save_experiment_summary
)
from model import (
    set_random_seeds,
    create_model,
    train_model,
    load_saved_model,
    get_training_summary,
    print_tensorflow_info
)
from data_preprocessing_multi_ue import (
    prepare_data,
    preprocess_pipeline
)
from data_loader_multi_ue import (
    load_all_multi_ue_datasets,
    analyze_multi_ue_dataset
)
from config_multi_ue import config_multi_ue
import pandas as pd
import numpy as np
from typing import Dict, Optional, Any
import datetime
import time
import sys
import os
os.environ['TF_USE_LEGACY_KERAS'] = '1'

# Standard library imports

# Third-party imports

# Import project modules (multi-user specific)

# Import project modules (base modules - reusable)

# Visualization (optional - may not be available)
try:
    from visualization import generate_all_plots
    VISUALIZATION_AVAILABLE = True
except ImportError:
    VISUALIZATION_AVAILABLE = False
    print("WARNING: visualization module not found. Plots will be skipped.")


# =============================================================================
# SECTION 1: SYSTEM INFORMATION
# =============================================================================

def print_system_info() -> None:
    """
    Print system information, library versions, and GPU availability.

    This is critical for research reproducibility. Reviewers may request
    exact environment details to replicate results.
    """
    print("\n" + "=" * 80)
    print("   PUCCH FORMAT 0 - MULTI-USER MACHINE LEARNING DECODER")
    print("   Research-Grade Implementation")
    print("=" * 80)
    print(
        f"\nTimestamp: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"Python: {sys.version.split()[0]}")
    print(f"NumPy: {np.__version__}")
    print(f"Pandas: {pd.__version__}")

    # TensorFlow info
    print_tensorflow_info()

    # Multi-user scenario info
    print(f"\n--- Multi-User Configuration ---")
    print(f"Scenario: {config_multi_ue.CURRENT_SCENARIO_KEY}")
    print(f"Number of Users: {config_multi_ue.NUM_USERS}")
    print(f"Target User m0: {config_multi_ue.TARGET_USER_M0}")
    print(f"Interferer m0s: {config_multi_ue.INTERFERER_M0S}")
    print("=" * 80 + "\n")


# =============================================================================
# SECTION 2: CHECK DATA FILES
# =============================================================================

def check_multi_ue_data_files(verbose: bool = True) -> bool:
    """
    Check if all required multi-user data files exist.

    Parameters:
    -----------
    verbose : bool, default=True
        If True, print file status

    Returns:
    --------
    all_found : bool
        True if all required files exist
    """

    if verbose:
        print("\n" + "=" * 80)
        print("CHECKING MULTI-USER DATA FILES")
        print("=" * 80)

    all_found = True
    found_count = 0
    missing_count = 0

    scenario = config_multi_ue.CURRENT_SCENARIO_KEY

    for snr in config_multi_ue.SNR_VALUES:
        filepath = config_multi_ue.get_data_filepath(snr, scenario=scenario)
        exists = os.path.exists(filepath)

        if exists:
            found_count += 1
            file_size = os.path.getsize(filepath) / (1024 * 1024)  # MB
            if verbose:
                print(
                    f"  [FOUND]   SNR {snr:3d} dB: {filepath} ({file_size:.1f} MB)")
        else:
            missing_count += 1
            all_found = False
            if verbose:
                print(f"  [MISSING] SNR {snr:3d} dB: {filepath}")

    if verbose:
        print(
            f"\nFound: {found_count}/{len(config_multi_ue.SNR_VALUES)} files")

        if not all_found:
            print("\n⚠️  WARNING: Some data files are missing!")
            print("Please run the MATLAB multi-user data generation script first.")
            print(
                f"Expected directory: {os.path.abspath(config_multi_ue.DATA_DIR)}")
            print(f"Expected pattern: pucch_f0_{scenario}_SNR_XdB.csv")

        print("=" * 80 + "\n")

    return all_found


# =============================================================================
# SECTION 3: MAIN PIPELINE
# =============================================================================

def run_multi_ue_pipeline(
    show_plots: bool = True,
    verbose: bool = True
) -> Optional[Dict[str, Any]]:
    """
    Run the complete Multi-User ML pipeline.

    This function executes all steps in order:
        1. Print system info and configuration
        2. Check and load multi-user data files
        3. Analyze training dataset
        4. Prepare data splits
        5. Preprocess data
        6. Create neural network model
        7. Train model
        8. Load best model
        9. Evaluate on all SNR values
        10. Generate classification reports
        11. Compare with correlation decoder
        12. Generate plots (if available)
        13. Save all results

    Parameters:
    -----------
    show_plots : bool, default=True
        If True, display plots during execution
        Set to False for batch/automated runs
    verbose : bool, default=True
        If True, print detailed progress information

    Returns:
    --------
    results : dict or None
        Dictionary containing all outputs:
        - 'model': Trained model
        - 'history': Training history
        - 'training_time': Training time in seconds
        - 'all_results': Evaluation results per SNR
        - 'comparison': NN vs Correlation comparison
        - 'training_summary': Summary of training
        - 'scenario': Multi-user scenario info

        Returns None if pipeline fails.
    """

    pipeline_start_time = time.time()

    # =========================================================================
    # STEP 1: System Information and Configuration
    # =========================================================================

    if verbose:
        print("\n")
        print("#" * 80)
        print("#" + " " * 25 + "STARTING MULTI-USER PIPELINE" + " " * 23 + "#")
        print("#" * 80)

    print_system_info()
    config_multi_ue.print_config()

    # Validate configuration
    if not config_multi_ue.validate_config():
        print("❌ ERROR: Configuration validation failed. Aborting.")
        return None

    # Create output directories
    config_multi_ue.create_directories()

    # =========================================================================
    # STEP 2: Set Random Seeds
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 1: Setting Random Seeds")
        print("=" * 80)

    set_random_seeds(seed=config_multi_ue.MASTER_SEED, verbose=True)

    # =========================================================================
    # STEP 3: Check and Load Data Files
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 2: Loading Multi-User Data")
        print("=" * 80)

    # Check files exist
    files_exist = check_multi_ue_data_files(verbose=True)

    if not files_exist:
        print("\n❌ ERROR: Required multi-user data files not found!")
        print("Please run the MATLAB multi-user data generation script first.")
        return None

    # Load all datasets
    try:
        datasets = load_all_multi_ue_datasets(
            snr_values=config_multi_ue.SNR_VALUES,
            scenario=config_multi_ue.CURRENT_SCENARIO_KEY,
            data_dir=config_multi_ue.DATA_DIR,
            validate=True,
            verbose=True
        )
    except Exception as e:
        print(f"\n❌ ERROR: Failed to load datasets: {e}")
        return None

    # Verify training SNR is available
    if config_multi_ue.TRAIN_SNR not in datasets:
        print(
            f"\n❌ ERROR: Training SNR {config_multi_ue.TRAIN_SNR} dB not loaded!")
        print(f"Available SNR values: {list(datasets.keys())}")
        return None

    # =========================================================================
    # STEP 4: Analyze Training Dataset
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 3: Analyzing Training Dataset")
        print("=" * 80)

    train_stats = analyze_multi_ue_dataset(
        X=datasets[config_multi_ue.TRAIN_SNR][0],
        y=datasets[config_multi_ue.TRAIN_SNR][1],
        scenario=config_multi_ue.CURRENT_SCENARIO_KEY,
        name=f"Training Data (SNR = {config_multi_ue.TRAIN_SNR} dB)",
        verbose=True
    )

    # Check for data quality issues
    if train_stats['num_nan'] > 0:
        print("⚠️  WARNING: NaN values found in training data!")
    if train_stats['num_inf'] > 0:
        print("⚠️  WARNING: Inf values found in training data!")
    if not train_stats['is_balanced']:
        print("⚠️  WARNING: Training data is not balanced!")

    # =========================================================================
    # STEP 5: Prepare Data Splits
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 4: Preparing Data Splits")
        print("=" * 80)

    try:
        X_train, y_train, X_val, y_val, X_test_dict, y_test_dict = prepare_data(
            datasets=datasets,
            train_snr=config_multi_ue.TRAIN_SNR,
            train_ratio=config_multi_ue.TRAIN_RATIO,
            random_seed=config_multi_ue.SKLEARN_SEED,
            verbose=True
        )
    except Exception as e:
        print(f"\n❌ ERROR: Failed to prepare data: {e}")
        return None

    # =========================================================================
    # STEP 6: Preprocess Data
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 5: Preprocessing Data")
        print("=" * 80)

    X_train_proc, X_val_proc, X_test_dict_proc, scaler = preprocess_pipeline(
        X_train=X_train,
        X_val=X_val,
        X_test_dict=X_test_dict,
        normalize=config_multi_ue.NORMALIZE_FEATURES,
        verbose=True
    )

    # =========================================================================
    # STEP 7: Create Neural Network Model
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 6: Creating Neural Network Model")
        print("=" * 80)

    model = create_model(
        input_size=config_multi_ue.INPUT_SIZE,
        hidden_layers=config_multi_ue.HIDDEN_LAYERS,
        output_size=config_multi_ue.OUTPUT_SIZE,
        hidden_activation=config_multi_ue.HIDDEN_ACTIVATION,
        output_activation=config_multi_ue.OUTPUT_ACTIVATION,
        dropout_rate=config_multi_ue.DROPOUT_RATE,
        use_dropout=config_multi_ue.USE_DROPOUT,
        kernel_initializer=config_multi_ue.KERNEL_INITIALIZER,
        learning_rate=config_multi_ue.LEARNING_RATE,
        momentum=config_multi_ue.MOMENTUM,
        use_nesterov=config_multi_ue.USE_NESTEROV,
        print_summary=True
    )

    # =========================================================================
    # STEP 8: Train Model
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 7: Training Model")
        print("=" * 80)

    model_filepath = config_multi_ue.get_model_filepath()

    try:
        history, training_time = train_model(
            model=model,
            X_train=X_train_proc,
            y_train=y_train,
            X_val=X_val_proc,
            y_val=y_val,
            epochs=config_multi_ue.NUM_EPOCHS,
            batch_size=config_multi_ue.BATCH_SIZE,
            model_filepath=model_filepath,
            verbose=1
        )
    except Exception as e:
        print(f"\n❌ ERROR: Training failed: {e}")
        return None

    # Get training summary
    training_summary = get_training_summary(history)

    # =========================================================================
    # STEP 9: Load Best Model
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 8: Loading Best Model")
        print("=" * 80)

    try:
        best_model = load_saved_model(filepath=model_filepath, verbose=True)
    except FileNotFoundError:
        print("⚠️  WARNING: Best model file not found. Using last training state.")
        best_model = model

    # =========================================================================
    # STEP 10: Evaluate on All SNR Values
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 9: Evaluating Model")
        print("=" * 80)

    all_results = evaluate_all_snr(
        model=best_model,
        X_test_dict=X_test_dict_proc,
        y_test_dict=y_test_dict,
        verbose=True
    )

    # =========================================================================
    # STEP 11: Generate Classification Reports
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 10: Classification Reports")
        print("=" * 80)

    reports = generate_all_classification_reports(
        all_results=all_results,
        verbose=True
    )

    # =========================================================================
    # STEP 12: Compare with Correlation Decoder
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 11: Comparing with Correlation Decoder")
        print("=" * 80)

    comparison = compare_nn_vs_correlation(
        model=best_model,
        X_test_dict=X_test_dict_proc,
        y_test_dict=y_test_dict,
        X_train=X_train_proc,
        y_train=y_train,
        verbose=True
    )

    # =========================================================================
    # STEP 13: Generate All Plots
    # =========================================================================

    if VISUALIZATION_AVAILABLE and show_plots:
        if verbose:
            print("\n" + "=" * 80)
            print("STEP 12: Generating Plots")
            print("=" * 80)

        try:
            from visualization import generate_all_plots
            generate_all_plots(
                history=history,
                all_results=all_results,
                comparison=comparison,
                show_plots=show_plots,
                verbose=True
            )
        except Exception as e:
            print(f"⚠️  WARNING: Plot generation failed: {e}")
    else:
        if verbose:
            print("\n" + "=" * 80)
            print("STEP 12: Skipping Plots")
            print("=" * 80)
            print("Visualization module not available or plots disabled.")

    # =========================================================================
    # STEP 14: Save All Results
    # =========================================================================

    if verbose:
        print("\n" + "=" * 80)
        print("STEP 13: Saving Results")
        print("=" * 80)

    # Save evaluation results CSV
    results_df = save_evaluation_results(
        all_results=all_results,
        comparison=comparison,
        filepath=os.path.join(
            config_multi_ue.RESULTS_DIR,
            config_multi_ue.RESULTS_FILENAME
        ),
        verbose=True
    )

    # Save confusion matrices
    save_confusion_matrices(
        all_results=all_results,
        filepath=os.path.join(
            config_multi_ue.RESULTS_DIR,
            "confusion_matrices_multi_ue.txt"
        ),
        verbose=True
    )

    # Save experiment summary
    save_experiment_summary(
        all_results=all_results,
        comparison=comparison,
        training_time=training_time,
        history=history,
        filepath=os.path.join(
            config_multi_ue.RESULTS_DIR,
            "experiment_summary_multi_ue.txt"
        ),
        verbose=True
    )

    # =========================================================================
    # FINAL SUMMARY
    # =========================================================================

    pipeline_time = time.time() - pipeline_start_time

    print("\n")
    print("#" * 80)
    print("#" + " " * 25 + "MULTI-USER PIPELINE COMPLETE" + " " * 21 + "#")
    print("#" * 80)

    print(
        f"\nTotal pipeline time: {pipeline_time:.1f} seconds ({pipeline_time/60:.2f} minutes)")
    print(
        f"\nTimestamp: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")

    # Training summary
    print(f"\n--- Training Summary ---")
    print(f"Epochs completed: {training_summary['epochs_completed']}")
    print(f"Training time: {training_time:.1f} seconds")
    print(f"Best validation accuracy: {training_summary['best_val_acc']:.2f}%  "
          f"(epoch {training_summary['best_epoch']})")

    # Results summary
    print(f"\n--- Multi-User Results Summary ---")
    print(f"Scenario: {config_multi_ue.CURRENT_SCENARIO_KEY}")
    print(f"Number of Users: {config_multi_ue.NUM_USERS}")
    print(f"Target User m0: {config_multi_ue.TARGET_USER_M0}")
    print(
        f"\n{'SNR (dB)': <10}{'NN Acc (%)': <12}{'Corr Acc (%)': <14}{'Gain (%)': <10}")
    print("-" * 46)
    for i, snr in enumerate(comparison['snr']):
        nn_acc = comparison['nn_accuracy'][i]
        corr_acc = comparison['corr_accuracy'][i]
        gain = nn_acc - corr_acc
        print(f"{snr: <10}{nn_acc: <12.2f}{corr_acc: <14.2f}{gain: <+10.2f}")
    print("-" * 46)

    # Average gain
    avg_gain = np.mean([comparison['nn_accuracy'][i] - comparison['corr_accuracy'][i]
                        for i in range(len(comparison['snr']))])
    print(f"\nAverage Gain: {avg_gain:+.2f}%")

    # Output files
    print(f"\n--- Output Files ---")
    print(f"Model: {model_filepath}")
    print(
        f"Results: {os.path.join(config_multi_ue.RESULTS_DIR, config_multi_ue.RESULTS_FILENAME)}")
    print(f"Plots: {config_multi_ue.PLOTS_DIR}")
    print(f"Logs: {config_multi_ue.LOGS_DIR}")
    print(
        f"Summary: {os.path.join(config_multi_ue.RESULTS_DIR, 'experiment_summary_multi_ue.txt')}")

    print("\n" + "#" * 80 + "\n")

    # Prepare return dictionary
    results = {
        'model': best_model,
        'history': history,
        'training_time': training_time,
        'training_summary': training_summary,
        'all_results': all_results,
        'comparison': comparison,
        'reports': reports,
        'results_df': results_df,
        'scaler': scaler,
        'X_train': X_train_proc,
        'y_train': y_train,
        'X_val': X_val_proc,
        'y_val': y_val,
        'X_test_dict': X_test_dict_proc,
        'y_test_dict': y_test_dict,
        'pipeline_time': pipeline_time,
        'scenario': config_multi_ue.CURRENT_SCENARIO_KEY,
        'num_users': config_multi_ue.NUM_USERS
    }

    return results


# =============================================================================
# SECTION 4: EVALUATION ONLY MODE
# =============================================================================

def run_multi_ue_evaluation_only(
    model_filepath: str = None,
    show_plots: bool = True,
    verbose: bool = True
) -> Optional[Dict[str, Any]]:
    """
    Run evaluation only using a previously trained multi-user model.

    This is useful when you want to re-evaluate or generate new plots
    without retraining the model.

    Parameters:
    -----------
    model_filepath : str, optional
        Path to the trained model
        Default: config_multi_ue.MODELS_DIR + config_multi_ue.MODEL_FILENAME
    show_plots : bool, default=True
        If True, display plots
    verbose : bool, default=True
        If True, print progress

    Returns:
    --------
    results : dict or None
        Dictionary containing evaluation results, or None if failed
    """

    if model_filepath is None:
        model_filepath = config_multi_ue.get_model_filepath()

    print("\n" + "=" * 80)
    print("MULTI-USER EVALUATION ONLY MODE")
    print("=" * 80)

    # Set seeds
    set_random_seeds(config_multi_ue.MASTER_SEED, verbose=True)

    # Check model exists
    if not os.path.exists(model_filepath):
        print(f"❌ ERROR: Model file not found: {model_filepath}")
        print("Please train a model first using run_multi_ue_pipeline()")
        return None

    # Load model
    try:
        model = load_saved_model(filepath=model_filepath, verbose=True)
    except Exception as e:
        print(f"❌ ERROR: Failed to load model: {e}")
        return None

    # Check data files
    if not check_multi_ue_data_files(verbose=True):
        return None

    # Load data
    try:
        datasets = load_all_multi_ue_datasets(verbose=True)
    except Exception as e:
        print(f"❌ ERROR: Failed to load data: {e}")
        return None

    # Prepare data
    try:
        X_train, y_train, X_val, y_val, X_test_dict, y_test_dict = prepare_data(
            datasets=datasets,
            verbose=True
        )
    except Exception as e:
        print(f"❌ ERROR: Failed to prepare data: {e}")
        return None

    # Preprocess
    X_train_proc, X_val_proc, X_test_dict_proc, scaler = preprocess_pipeline(
        X_train=X_train,
        X_val=X_val,
        X_test_dict=X_test_dict,
        verbose=True
    )

    # Evaluate
    all_results = evaluate_all_snr(
        model=model,
        X_test_dict=X_test_dict_proc,
        y_test_dict=y_test_dict,
        verbose=True
    )

    # Classification reports
    reports = generate_all_classification_reports(
        all_results=all_results,
        verbose=True
    )

    # Compare with correlation
    comparison = compare_nn_vs_correlation(
        model=model,
        X_test_dict=X_test_dict_proc,
        y_test_dict=y_test_dict,
        X_train=X_train_proc,
        y_train=y_train,
        verbose=True
    )

    # Save results
    save_evaluation_results(
        all_results=all_results,
        comparison=comparison,
        verbose=True
    )

    print("\n" + "=" * 80)
    print("MULTI-USER EVALUATION COMPLETE")
    print("=" * 80 + "\n")

    results = {
        'model': model,
        'all_results': all_results,
        'comparison': comparison,
        'reports': reports
    }

    return results


# =============================================================================
# SECTION 5: SCRIPT ENTRY POINT
# =============================================================================

if __name__ == "__main__":
    """
    Main entry point for Multi-User PUCCH Format 0 ML Decoder.

    Usage:
        python main_multi_ue.py              # Run full pipeline
        python main_multi_ue.py --eval-only  # Run evaluation only
        python main_multi_ue.py --no-plots   # Run without displaying plots
        python main_multi_ue.py --help       # Show help
    """

    # Parse simple command line arguments
    show_plots = True
    eval_only = False

    if len(sys.argv) > 1:
        for arg in sys.argv[1:]:
            if arg == "--eval-only":
                eval_only = True
            elif arg == "--no-plots":
                show_plots = False
            elif arg == "--help":
                print("\nUsage: python main_multi_ue.py [options]")
                print("\nOptions:")
                print("  --eval-only   Run evaluation only (requires trained model)")
                print("  --no-plots    Run without displaying plots")
                print("  --help        Show this help message")
                print("\nMulti-User PUCCH Format 0 ML Decoder:")
                print("  - Decodes target user in presence of interference")
                print("  - Supports 2-user and 3-user scenarios")
                print("  - Compares with correlation-based baseline")
                sys.exit(0)
            else:
                print(f"Unknown argument: {arg}")
                print("Use --help for usage information")
                sys.exit(1)

    # Run selected mode
    if eval_only:
        results = run_multi_ue_evaluation_only(show_plots=show_plots)
    else:
        results = run_multi_ue_pipeline(show_plots=show_plots)

    # Check if pipeline completed successfully
    if results is not None:
        print("✅ Multi-user pipeline completed successfully!")
        print(f"\nResearch Data Saved To: {config_multi_ue.RESULTS_DIR}")
        print("Ready for analysis and paper writing.")
    else:
        print("❌ Pipeline failed. Please check the error messages above.")
        sys.exit(1)
